[colors]
deeppink = "deeppink"
skyblue = "skyblue"
lightslategray = "lightslategray"
gainsboro = "gainsboro"
darkviolet = "darkviolet"
rosybrown = "rosybrown"
orchid = "orchid"
yellowgreen = "yellowgreen"
thistle = "thistle"
greenyellow = "greenyellow"
snow = "snow"
mediumaquamarine = "mediumaquamarine"
cornflowerblue = "cornflowerblue"
beige = "beige"
saddlebrown = "saddlebrown"
teal = "teal"
black = "black"
chocolate = "chocolate"
palegoldenrod = "palegoldenrod"
magenta = "magenta"
forestgreen = "forestgreen"
crimson = "crimson"
khaki = "khaki"
mediumslateblue = "mediumslateblue"
darkslategrey = "darkslategrey"
wheat = "wheat"
ghostwhite = "ghostwhite"
darkred = "darkred"
lightseagreen = "lightseagreen"
blueviolet = "blueviolet"
darkmagenta = "darkmagenta"
pink = "pink"
springgreen = "springgreen"
blanchedalmond = "blanchedalmond"
darkslategray = "darkslategray"
lightgray = "lightgray"
lightyellow = "lightyellow"
darkslateblue = "darkslateblue"
rebeccapurple = "rebeccapurple"
darkblue = "darkblue"
darkseagreen = "darkseagreen"
mediumvioletred = "mediumvioletred"
purple = "purple"
darksalmon = "darksalmon"
olivedrab = "olivedrab"
sienna = "sienna"
whitesmoke = "whitesmoke"
lightcoral = "lightcoral"
slateblue = "slateblue"
lightskyblue = "lightskyblue"
lightgreen = "lightgreen"
blue = "blue"
aliceblue = "aliceblue"
lemonchiffon = "lemonchiffon"
mediumseagreen = "mediumseagreen"
steelblue = "steelblue"
lightgoldenrodyellow = "lightgoldenrodyellow"
cadetblue = "cadetblue"
darkgray = "darkgray"
lightpink = "lightpink"
darkturquoise = "darkturquoise"
lightsalmon = "lightsalmon"
lightblue = "lightblue"
turquoise = "turquoise"
hotpink = "hotpink"
olive = "olive"
white = "white"
ivory = "ivory"
linen = "linen"
darkgrey = "darkgrey"
lavender = "lavender"
midnightblue = "midnightblue"
bisque = "bisque"
darkgreen = "darkgreen"
darkkhaki = "darkkhaki"
green = "green"
indigo = "indigo"
dimgray = "dimgray"
papayawhip = "papayawhip"
peru = "peru"
salmon = "salmon"
slategray = "slategray"
plum = "plum"
coral = "coral"
goldenrod = "goldenrod"
limegreen = "limegreen"
navy = "navy"
darkolivegreen = "darkolivegreen"
cyan = "cyan"
mintcream = "mintcream"
chartreuse = "chartreuse"
honeydew = "honeydew"
peachpuff = "peachpuff"
seashell = "seashell"
sandybrown = "sandybrown"
lawngreen = "lawngreen"
deepskyblue = "deepskyblue"
palevioletred = "palevioletred"
lightslategrey = "lightslategrey"
oldlace = "oldlace"
azure = "azure"
violet = "violet"
aqua = "aqua"
darkcyan = "darkcyan"
royalblue = "royalblue"
mistyrose = "mistyrose"
tomato = "tomato"
lightcyan = "lightcyan"
lavenderblush = "lavenderblush"
moccasin = "moccasin"
seagreen = "seagreen"
mediumorchid = "mediumorchid"
burlywood = "burlywood"
antiquewhite = "antiquewhite"
red = "red"
orange = "orange"
mediumblue = "mediumblue"
darkorange = "darkorange"
floralwhite = "floralwhite"
maroon = "maroon"
gray = "gray"
firebrick = "firebrick"
dimgrey = "dimgrey"
gold = "gold"
dodgerblue = "dodgerblue"
lightgrey = "lightgrey"
fuchsia = "fuchsia"
lime = "lime"
navajowhite = "navajowhite"
grey = "grey"
silver = "silver"
mediumturquoise = "mediumturquoise"
brown = "brown"
aquamarine = "aquamarine"
palegreen = "palegreen"
powderblue = "powderblue"
mediumpurple = "mediumpurple"
slategrey = "slategrey"
darkgoldenrod = "darkgoldenrod"
tan = "tan"
orangered = "orangered"
indianred = "indianred"
lightsteelblue = "lightsteelblue"
darkorchid = "darkorchid"
mediumspringgreen = "mediumspringgreen"
paleturquoise = "paleturquoise"
yellow = "yellow"
cornsilk = "cornsilk"
